- name: Get Azure Disks
  ansible.builtin.include_tasks:
    file: get_azure_disks.yml
  tags:
    - get_disks

- name: Provision Disks
  ansible.builtin.include_tasks:
    file: provision_disks.yml
  tags:
    - provision_disks
